const jobs = [
  {
    id: "ssc-cpo-2026",
    org: "SSC",
    category: "SSC",
    title: "SSC CPO SI Recruitment 2026",
    posts: "1,871",
    lastDate: "30 September 2026",
    qualification: "Graduation",
    age: "Official Notification के अनुसार",
    fee: "Official Notification देखें",
    selection: "Paper-I, Physical Test, Paper-II और निर्धारित चरण",
    salary: "Pay Level के अनुसार",
    startDate: "10 September 2026",
    official: "https://ssc.gov.in/",
    apply: "https://ssc.gov.in/",
    notification: "https://ssc.gov.in/",
    status: "Application Open"
  },

  {
    id: "ssc-chsl-2026",
    org: "SSC",
    category: "SSC",
    title: "SSC CHSL Recruitment 2026",
    posts: "2,536",
    lastDate: "07 October 2026",
    qualification: "12वीं / पद के अनुसार",
    age: "Official Notification के अनुसार",
    fee: "Official Notification देखें",
    selection: "Tier / Skill Test — पद के अनुसार",
    salary: "Pay Level के अनुसार",
    startDate: "Official Notification के अनुसार",
    official: "https://ssc.gov.in/",
    apply: "https://ssc.gov.in/",
    notification: "https://ssc.gov.in/",
    status: "Application Open"
  },

  {
    id: "upsc-eng-2027",
    org: "UPSC",
    category: "UPSC",
    title: "UPSC Engineering Services Examination 2027",
    posts: "480",
    lastDate: "06 October 2026",
    qualification: "Engineering Degree / संबंधित योग्यता",
    age: "Official Notification के अनुसार",
    fee: "Official Notification देखें",
    selection: "Prelims / Mains / Personality Test",
    salary: "Service / Pay Matrix के अनुसार",
    startDate: "Official Notification के अनुसार",
    official: "https://upsc.gov.in/",
    apply: "https://upsconline.nic.in/",
    notification: "https://upsc.gov.in/",
    status: "Application Open"
  },

  {
    id: "ibps-rrb-2026",
    org: "IBPS",
    category: "Banking",
    title: "IBPS RRB CRP-RRBs-XV 2026",
    posts: "13,706",
    lastDate: "27 September 2026",
    qualification: "पद के अनुसार Graduation / अन्य योग्यता",
    age: "Official Notification के अनुसार",
    fee: "Official Notification देखें",
    selection: "Prelims / Main / Interview — पद के अनुसार",
    salary: "पद के अनुसार",
    startDate: "Official Notification के अनुसार",
    official: "https://www.ibps.in/",
    apply: "https://www.ibps.in/",
    notification: "https://www.ibps.in/",
    status: "Application Open"
  },

  {
    id: "crpf-sports-2026",
    org: "CRPF",
    category: "Defence",
    title: "CRPF Sports Quota Recruitment 2026",
    posts: "521",
    lastDate: "11 November 2026",
    qualification: "Sports qualification + notification में दी गई योग्यता",
    age: "Official Notification के अनुसार",
    fee: "Official Notification देखें",
    selection: "Sports Trial / Physical / Medical आदि",
    salary: "Pay Level के अनुसार",
    startDate: "Official Notification के अनुसार",
    official: "https://rect.crpf.gov.in/",
    apply: "https://rect.crpf.gov.in/",
    notification: "https://rect.crpf.gov.in/",
    status: "Recruitment Open"
  },

  {
    id: "uppsc-pcs-2026",
    org: "UPPSC",
    category: "UP",
    title: "UPPSC PCS 2026",
    posts: "Official Notification के अनुसार",
    lastDate: "Official Notification देखें",
    qualification: "Graduation / post-specific qualification",
    age: "Official Notification के अनुसार",
    fee: "Official Notification देखें",
    selection: "Prelims / Mains / Interview",
    salary: "Post के अनुसार",
    startDate: "Official Notification के अनुसार",
    official: "https://uppsc.up.nic.in/",
    apply: "https://uppsc.up.nic.in/",
    notification: "https://uppsc.up.nic.in/",
    status: "Check Official Notice"
  },

  {
    id: "railway-apprentice-2026",
    org: "Railway",
    category: "Railway",
    title: "Southern Railway Apprentice Recruitment 2026",
    posts: "Official Notification के अनुसार",
    lastDate: "Official Notification देखें",
    qualification: "10वीं + ITI / trade के अनुसार",
    age: "Official Notification के अनुसार",
    fee: "Official Notification देखें",
    selection: "Merit / Apprenticeship rules के अनुसार",
    salary: "Stipend — notification के अनुसार",
    startDate: "Official Notification के अनुसार",
    official: "https://sr.indianrailways.gov.in/",
    apply: "https://sr.indianrailways.gov.in/",
    notification: "https://sr.indianrailways.gov.in/",
    status: "Check Official Notice"
  }
];
